### PR TITLE
Python 3 compatibility, sort of, maybe

### PR DESCRIPTION
**Pull request by eevee**
The first commit is entirely automated, using `futurize --stage1` (a subset of `2to3` that avoids doing anything that would break 2).  Looks like it accidentally nuked the CRs from a couple files, which has made this diff look much worse than it actually is.

Successfully builds both pokered and pokeyellow using CPython 2.7 and CPython 3.5 and maybe even a PyPy in there somewhere.  Makes me happy since bare `python` is Python 3 on Arch.

The test suite appears to be on fire, which makes it hard to tell if I broke anything.  May keep poking at this, though.

### CODE REVIEW

**Comment by kanzure** [comment]
Well, one way to fix the test suites is to keep deleting code and tests until everything is "passing". I guess we should setup travis-ci, since we are trying to not live in the dark ages and such.

**Comment by eevee** [comment]
Oho, believe me, I _love_ deleting stuff that no one can justify keeping around.  :D

**Comment by PikalaxALT** [comment]
Relative imports render poketools unusable as a git submodule.

**Comment by eevee** [comment]
That sounds backwards; relative imports exist _for_ cases like submodules.

**Comment by Sanqui** [comment]
This is probably the issue @PikalaxALT ran into.
```
sanky@suguri:~/romhacking/gb/pokered$ make PYTHON=python2
rgbasm -D _RED -h -o audio_red.o audio.asm
Traceback (most recent call last):
  File "extras/pokemontools/gfx.py", line 7, in <module>
    from . import png
ValueError: Attempted relative import in non-package
Makefile:51: recipe for target 'gfx/AB.2bpp' failed
make: *** [gfx/AB.2bpp] Error 1
```
```
sanky@suguri:~/romhacking/gb/pokered$ make PYTHON=python3
Traceback (most recent call last):
  File "extras/pokemontools/gfx.py", line 7, in <module>
    from . import png
SystemError: Parent module '' not loaded, cannot perform relative import
Makefile:51: recipe for target 'gfx/AB.2bpp' failed
make: *** [gfx/AB.2bpp] Error 1
```

**Comment by kemenaran** [comment]
@PikalaxALT For reference, and for other people reading this page, I worked around this "can't relative import" error by invoking the tools as `python -m pokemontools.gbz80disasm` (rather than for instance `python pokemontools/gbz80disasm.py`).

**Pull request merged**
